---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Dylan Malandain.
--- DateTime: 29/10/2019 02:40
---

---@class RageUIRZ
RageUIRZ = {}

---@class Item
RageUIRZ.Item = {}

---@class Panel
RageUIRZ.Panel = {}

---@class Window
RageUIRZ.Window = {}

---@class RMenuRZ
RMenuRZ = setmetatable({}, RMenuRZ)

---@type table
local TotalMenus = {}

---Add
---@param Type string
---@param Name string
---@param Menu table
---@return RMenuRZ
---@public
function RMenuRZ.Add(Type, Name, Menu)
    if RMenuRZ[Type] ~= nil then
        RMenuRZ[Type][Name] = {
            Menu = Menu
        }
    else
        RMenuRZ[Type] = {}
        RMenuRZ[Type][Name] = {
            Menu = Menu
        }
    end
    return table.insert(TotalMenus, Menu)
end

---Get
---@param Type string
---@param Name string
---@return table
---@public
function RMenuRZ:Get(Type, Name)
    if self[Type] ~= nil and self[Type][Name] ~= nil then
        return self[Type][Name].Menu
    end
end

---GetType
---@param Type string
---@return table
---@public
function RMenuRZ:GetType(Type)
    if self[Type] ~= nil then
        return self[Type]
    end
end

---Settings
---@param Type string
---@param Name string
---@param Settings string
---@param Value any optional
---@return void
---@public
function RMenuRZ:Settings(Type, Name, Settings, Value)
    if Value ~= nil then
        self[Type][Name][Settings] = Value
    else
        return self[Type][Name][Settings]
    end
end

---Delete
---@param Type string
---@param Name string
---@return void
---@public
function RMenuRZ:Delete(Type, Name)
    self[Type][Name] = nil
    collectgarbage()
end

---DeleteType
---@param Type string
---@return void
---@public
function RMenuRZ:DeleteType(Type)
    self[Type] = nil
    collectgarbage()
end
